app/mod_dashboard/controllers.py
from flask import Blueprint, request, render_template, jsonify
from app.mod_dashboard.models import Dashboard
from app.mod_device.models import Device
from app.mod_vpn.models import VPN

mod_dashboard = Blueprint('dashboard', __name__, url_prefix='/dashboard')
dashboard = Dashboard()
device = Device()
vpn = VPN()


@mod_dashboard.route("/", methods=["GET"])
def index():
    interfaces = device.interfaces()
    vpns = vpn.get_list()
    return render_template("dashboard/status.html", interfaces=interfaces, vpns=vpns)

app/mod_device/controllers.py
from flask import Blueprint, request, render_template, jsonify, redirect, url_for
from app.mod_device.models import Device

mod_device = Blueprint('device', __name__, url_prefix='/device')
device = Device()

@mod_device.route('/interfaces', methods=["GET"])
def interfaces():
    ifcfg = device.interfaces()
    if ifcfg is not None:
        return jsonify(ifcfg)

@mod_device.route("/connection", methods=["GET"])
def connection():
    is_online = device.check_internet()
    message = {"message": None, "status": False}
    if is_online:
        message["message"] = "You are connected to the internet!"
    else:
        message["message"] = "You are offline!"
    message["active"] = is_online
    return jsonify(message)

app/mod_page/controllers.py
from flask import Blueprint, render_template

mod_page = Blueprint('page', __name__, url_prefix='/')


@mod_page.route("/", methods=["GET"])
def index():
    return render_template("home/index.html")


@mod_page.route("how-it-works", methods=["GET"])
def how():
    return render_template("home/how.html")

app/mod_vpn/controllers.py
from flask import Blueprint, jsonify, request
from app.mod_vpn.models import VPN
mod_vpn = Blueprint('vpn', __name__, url_prefix='/vpn')
vpn = VPN()


@mod_vpn.route("/", methods=["GET"])
def index():
    response = {"data": list()}
    response["data"] = vpn.get_list()
    return jsonify(response)


@mod_vpn.route("/external_ip", methods=["GET"])
def external_ip():
    ip = vpn.external_ip()
    return jsonify({"ip": ip})


@mod_vpn.route("/connect", methods=["POST"])
def connect():
    vpn_name = request.form.get("vpn")
    response = vpn.connect(vpn_name)
    return jsonify(response)

app/templates/layout/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WIFI SHIELD - AP HOTSPOT</title>

    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='assets/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/app/css/jumbotron-narrow.css') }}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script>
      var URL_WIFI_SCAN = "{{ url_for('wifi.scan') }}";
      var URL_VPN_INDEX = "{{ url_for('vpn.index') }}";
      var URL_DEVICE_CONNECTION = "{{ url_for('device.connection') }}";
      var URL_VPN_CONNECT = "{{ url_for('vpn.connect') }}";
    </script>
  </head>
  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation">
              <a href="{{ url_for("page.index") }}">Home</a>
            </li>
            <li role="presentation">
              <a href="{{ url_for("wifi.connect") }}">Wifi</a>
            </li>
            <li role="presentation">
              <a href="{{ url_for("dashboard.index") }}">Dashboard</a>
            </li>
          </ul>
        </nav>
        <h3 class="text-muted">WIFI SHIELD</h3>
      </div>
      {% block body %}
      {% endblock %}
      <footer class="footer">
        <p>&copy; 2016 Makerhanoi.</p>
      </footer>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ url_for('static', filename='assets/app/js/jquery.min.js') }}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ url_for('static', filename='assets/bootstrap/js/bootstrap.min.js') }}"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>